# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt-get install jq git -y
          sudo npm i -g @adguard/hostlist-compiler
          git clone https://github.com/uklans/cache-domains.git .overlay/cache-domains
          
      # pushes changes    
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output.txt
          git commit -m "generated"
          git push
              
      - name: Cache
        uses: actions/cache@v2.1.2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: /usr/lib/node_modules/@adguard/hostlist-compiler .overlay/
          # An explicit key for restoring and saving the cache
          key: hostlist-compiler
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          restore-keys: hostlist-compiler
